FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    git \
    git-lfs \
    ffmpeg \
    libsm6 \
    libxext6 \
    cmake \
    rsync \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir pip -U && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit", "run", "BartBot.py", "--server.port=7860", "--server.address=0.0.0.0"]
